# Generated by Django 4.1 on 2024-05-30 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0002_customer_order_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="shipped_date",
            field=models.DateField(db_index=True, default=datetime.date(2024, 1, 1)),
        ),
        migrations.AlterField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
